# Generated by Django 4.2.25 on 2025-10-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('watchlist', 'Watchlist'), ('watching', 'Watching'), ('watched', 'Watched')], default='watchlist', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='movies/'),
        ),
    ]
