# Generated by Django 4.2.25 on 2025-10-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_status_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('watchlist', 'Watchlist'), ('watching', 'Watching'), ('watched', 'Watched')], default='select', max_length=20),
        ),
    ]
