# Generated by Django 4.2.25 on 2025-10-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='stars',
        ),
    ]
