# Generated by Django 4.2.25 on 2025-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_recommendedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedmovie',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recommendedmovie',
            name='typeOfFilm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
