# Generated by Django 4.2.25 on 2025-10-27 10:50

from django.db import migrations
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_recommendedmovie_genre_recommendedmovie_typeoffilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='embedding',
            field=VectorField(blank=True, dimensions=3, null=True),
        ),
    ]
