# Generated by Django 4.2.25 on 2025-10-27 10:57

from django.db import migrations
from pgvector.django.vector import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_review_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='embedding',
            field=VectorField(blank=True, dimensions=153, null=True),
        ),
    ]
