# Generated by Django 4.2.25 on 2025-10-28 12:09

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_review_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='embedding',
            new_name='reviewEmbedding',
        ),
        migrations.AddField(
            model_name='movie',
            name='titleEmb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=153, null=True),
        ),
    ]
