# Generated by Django 4.2.25 on 2025-10-28 13:36

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_rename_embedding_review_reviewembedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='titleEmb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
