# Generated by Django 4.2.25 on 2025-10-28 13:59

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_movie_titleemb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='titleEmb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
