# Generated by Django 4.2.25 on 2025-10-28 14:01

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_movie_titleemb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewEmbedding',
        ),
        migrations.AddField(
            model_name='review',
            name='titleEmb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
