# Generated by Django 4.2.25 on 2025-10-28 18:26

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_remove_review_reviewembedding_review_titleemb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='titleEmb',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=96, null=True),
        ),
    ]
