# Generated by Django 4.2.25 on 2025-10-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_titleemb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titleEmb',
            new_name='revieEmb',
        ),
    ]
