# Generated by Django 4.2.25 on 2025-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_rename_titleemb_review_revieemb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
