# Generated by Django 4.2.25 on 2025-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_remove_movie_image_movie_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
