# Generated by Django 4.2.25 on 2025-11-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_movie_cast_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(blank=True),
        ),
    ]
