# Generated by Django 4.2.25 on 2025-11-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='titleEmb',
        ),
        migrations.RemoveField(
            model_name='review',
            name='revieEmb',
        ),
    ]
